{ repoRoot, inputs, pkgs, lib, system }:

lib.iogx.mkShell {

  welcomeMessage = "Marlowe withdraw dapp";

  packages = [
    pkgs.prefetch-npm-deps
    pkgs.nodejs-18_x
    pkgs.nodejs-18_x.pkgs.webpack
    pkgs.nodejs-18_x.pkgs.webpack-cli
    pkgs.python39
  ];

  scripts.gen-npm-deps-hash = {
    group = "marlowe-payouts";
    description = "Run this whenever package-json.lock changes.";
    exec = ''
      cd "$(git rev-parse --show-toplevel)"
      echo "# This file was generated by prefetch-npm-deps" > nix/gen/npm-deps-hash.nix
      echo "\"$(prefetch-npm-deps package-lock.json)\"" >> nix/gen/npm-deps-hash.nix
    '';
  };

  preCommit = {
    shellcheck.enable = true;
    nixpkgs-fmt.enable = true;
  };
}
