# This file has been generated by node2nix 1.11.1. Do not edit!

{ iogxRepoRoot, repoRoot, inputs, inputs', pkgs, system, lib }:

let

  nodejs = pkgs.nodejs-18_x;
  npmlock2nix = import inputs'.npmlock2nix { inherit pkgs; };

in

npmlock2nix.v2.build {
  inherit nodejs;
  src = ./../..;
  installPhase = "cp -r dist $out";
  buildCommands = [
    # This line is needed to prevent the error:
    #   Internal Error: EACCES: permission denied, mkdir '/homeless-shelter'
    # See https://github.com/NixOS/nix/issues/670#issuecomment-1211700127
    "export HOME=$(pwd)"
    "echo $HOME"
    "npm run build"
    "cp -r public/* dist/"
  ];
}
